exec-once=quickshell
exec-once=sh -c "swayidle -w before-sleep 'qs -p ~/nixdotfiles/config/quickshell/LockScreen.qml' lock 'qs -p ~/nixdotfiles/config/quickshell/LockScreen.qml'"
bind=SUPER,d,spawn,qs -p ~/nixdotfiles/config/quickshell/qsLauncher.qml
bind=SUPER+SHIFT,d,spawn,sh -c 'python3 ~/nixdotfiles/config/quickshell/applauncher/parseDesktop.py'

bind=SUPER+ALT,l,spawn, qs -p ~/nixdotfiles/config/quickshell/LockScreen.qml
bind=SUPER,r,reload_config
bind=SUPER,x,spawn,foot
bind=SUPER,s,spawn,thunar
bind=SUPER,e,spawn,sh -c 'grim -g "$(slurp)" - | wl-copy'
bind=SUPER+ALT,m,quit
bind=SUPER,q,killclient,
bind=SUPER+SHIFT,q,killclient,force
bind=SUPER,b,spawn,firefox


bind=NONE,XF86MonBrightnessDown, spawn, brightnessctl set 10%-
bind=NONE,XF86MonBrightnessUp,   spawn, brightnessctl set 10%+
bind=NONE,XF86AudioLowerVolume,  spawn, wpctl set-volume @DEFAULT_SINK@ 3%-
bind=NONE,XF86AudioRaiseVolume,  spawn, wpctl set-volume @DEFAULT_SINK@  3%+
bind=NONE,XF86AudioMute,         spawn, wpctl set-mute @DEFAULT_SINK@  toggle

# switch window focus//general navigation
bind=SUPER,space,focusstack,next
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,rightw
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down
# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER,m,togglefloating,
bind=SUPER,f,togglefullscreen,
bind=SUPER+SHIFT,F,togglefakefullscreen,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=alt,e,toggle_scratchpad
# switch layout
bind=SUPER,n,switch_layout

# tag switch
# only switch with an active window

bind=SUPER+SHIFT,j,viewtoleft_have_client,0
bind=SUPER+SHIFT,l,viewtoright_have_client,0

bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
#bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
### Unused
# monitor switch
#bind=alt+shift,Left,focusmon,left
#bind=alt+shift,Right,focusmon,right
#bind=SUPER+Alt,Left,tagmon,left
#bind=SUPER+Alt,Right,tagmon,right

#scroller layout
#bind=ALT,e,set_proportion,1.0
#bind=ALT,x,switch_proportion_preset,


# no idea waht this does bind=ALT,a,togglemaximizescreen,













