layerrule=noanim:1,noblur:1,layer_name:selection

layerrule=animation_type_open:slide,animation_type_close:slide,noblur:0,layer_name:launcher

layerrule=animation_type_open:zoom,animation_type_close:zoom,noblur:0,layer_name:volumeIndicator

layerrule=animation_type_open:fade,animation_type_close:fade,noblur:0,layer_name:powerScreenQS
