
font=JetBrainsMono Nerd Font:size=11.4
# font-bold=<bold variant of regular font>
# font-italic=<italic variant of regular font>
# font-bold-italic=<bold+italic variant of regular font>
# font-size-adjustment=0.5
# line-height=<font metrics>
# letter-spacing=0
# horizontal-letter-offset=0
# vertical-letter-offset=0
# underline-offset=<font metrics>
# underline-thickness=<font underline thickness>
# strikeout-thickness=<font strikeout thickness>
# box-drawings-uses-font-glyphs=no
# dpi-aware=no
# gamma-correct-blending=no



[colors-dark]
background=1b1e25
foreground=c6c6c8
regular0=1b1e25
regular1=967786
regular2=7293A9
regular3=B28999
regular4=83A6BF
regular5=D5A5AA
regular6=DEC386
regular7=c6c6c8
bright0=626878
bright1=967786
bright2=7293A9
bright3=B28999
bright4=83A6BF
bright5=D5A5AA
bright6=DEC386
bright7=c6c6c8
alpha=1.0


[cursor]
style=block
blink=yes
blink-rate=800
beam-thickness=1

